name: Doxygen Documentation Check

on:
  push:
    branches:
    - 'Aadit_Doxygen_Trial'
  workflow_dispatch:

jobs:
  build-doxygen:
      runs-on: ubuntu-20.04 
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

#Running the Doxygen Documentation
      - name: Run through the Doxygen Documentation
        id: doxygen
        run: |
          sudo apt-get install doxygen
          mkdir -p build/gh_pages/doxygen_doc
          doxygen
          
      