name: Doxygen Documentation Check

on:
  push:
    branches:
    - 'Aadit_Doxygen_Trial'
  workflow_dispatch:

jobs:
  build-doxygen:
      runs-on: ubuntu-20.04 
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Run through the Doxygen Documentation
        id: doxygen
        run: |
          mkdir -p build/gh_pages
          doxygen || echo "DOXYGEN FAILED WITH EXIT CODE $?"

      - name: Display error messages
        if: failure()
        run: | 
          echo "ERROR MESSAGES:"
          cat doxygen.log
        env:
          DOXYGEN_LOG_FILE: doxygen.log
        
      - name: Display success message
        if: success()
        run: echo "NO ERRORS FOUND!"






          
      