name: Doxygen Documentation Check

# Controls when the workflow will run
on:
  #Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "Aadit_Doxygen_Trial" ]
    #pull_request:
    #branches: [ "Aadit_Doxygen_Trial" ]

  #merge_group:
	#type: [checks_requested]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    doxygen:
    #Uses the Ubuntu version 20.04
    runs-on: ubuntu-20.04 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Setup github to checkout the code from the repo
       -name: Checkout code

       # Specifies the action of checking out code from the Github repository
            uses: actions/checkout@v3

            # Make doxygen documentation using the shell script
	    - name: Make doxygen documentation
              id: doxygen

	    # The shell script will generate the doxygen document
              uses:./doxygen_errors.sh
	      on: error

	    # Report an error if last step failed
	    - name: Report errors  
	      if: failure()
           # Tool for automating tasks in a GitHub repository, such as creating issues, commenting on pull requests, or modifying files.
   	      uses: actions/github-script@v6

 	      env:
     		   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     	      with:
              script: |	     
              
	   const issueComment = 'WARNINGS GENERATED, PLEASE CHECK LOGS.';
 			github.issues.createComment({
           			 issue_number: context.issue.number,
            			 owner: context.repo.owner,
           			 repo: context.repo.repo,
          			 body: issueComment
          		       });
