name: Doxygen Documentation Check

on:
  push:
    branches: 
    - 'Aadit_Doxygen_Trial'
  workflow_dispatch:

jobs:
  build-doxygen:
      runs-on: ubuntu-20.04 
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Make a doxygen_error.txt file
        run: |
          touch doxygen_errors.txt

      - name: Run through the Doxygen Documentation
        id: doxygen
        run: |
          mkdir -p build/gh_pages
          doxygen 2> doxygen_errors.txt
      
      - name: Check for errors in the Doxygen Documentation
        run: |
          if [ -s doxygen_errors.txt ]
          then
            echo "Errors found in the Doxygen Documentation:"
            cat doxygen_errors.txt
            exit 1
          else
            echo "No errors found in the Doxygen Documentation"
            exit 0
          fi









          
      