name: Doxygen Documentation Check

on:
  push:
    branches:
    - 'Aadit_Doxygen_Trial'
  workflow_dispatch:

jobs:
  build-doxygen:
      runs-on: ubuntu-20.04 
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Make a doxygen_error.txt file
        run: |
          touch doxygen_errors.txt

      - name: Run through the Doxygen Documentation
        id: doxygen
        run: |
          mkdir -p build/gh_pages
          doxygen || echo "Doxygen failed with an exit code of $?"
          doxygen 2> doxygen_errors.txt

      - name: Errors in the Doxygen Documentation
        if: failure()
        run: |
          echo "errors, File displayed:"
          cat doxygen_errors.txt
      
          









          
      