name: Doxygen Documentation Check

on:
  push:
    branches:
    - 'Aadit_Doxygen_Trial'
  workflow_dispatch:

jobs:
  build-doxygen:
      runs-on: ubuntu-20.04 
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install doxygen

      - name: Run through the Doxygen Documentation
        id: doxygen
        run: |
          mkdir -p build/gh_pages
          doxygen 
          doxygen 2> doxygen_errors.txt

      - name: Display any error messages
        if: failure
        run: |
          echo "ERROR MESSAGES:"
          if [ -f "doxygen_errors.txt" ]; then
            cat doxygen_errors.txt
          else
            echo "NO ERROR MESSAGES FOUND!"







          
      